Repository FindYou-Kuit/FindYou-Server, pull requests merged in 2025-01, with the labels that each got.

#10 [feat] #9 response, controllerAdvice 구현
  src/main/java/com/kuit/findyou/domain/auth/TestController.java
  src/main/java/com/kuit/findyou/global/common/exception/BadRequestException.java
  src/main/java/com/kuit/findyou/global/common/exception_handler/GlobalControllerAdvice.java
  src/main/java/com/kuit/findyou/global/common/response/BaseErrorResponse.java
  src/main/java/com/kuit/findyou/global/common/response/BaseResponse.java
  src/main/java/com/kuit/findyou/global/common/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/kuit/findyou/global/common/response/status/ResponseStatus.java
  src/main/resources/application.yml
Labels: enhancement, 익환

#12 [Feat] 엔티티 설계
  src/main/java/com/kuit/findyou/FindyouApplication.java
  src/main/java/com/kuit/findyou/domain/auth/model/User.java
  src/main/java/com/kuit/findyou/domain/auth/repository/UserRepository.java
  src/main/java/com/kuit/findyou/domain/report/controller/ReportController.java
  src/main/java/com/kuit/findyou/domain/report/dto/ProtectingReportInfoDTO.java
  src/main/java/com/kuit/findyou/domain/report/dto/ReportInfoDTO.java
  src/main/java/com/kuit/findyou/domain/report/model/AnimalFeature.java
  src/main/java/com/kuit/findyou/domain/report/model/Breed.java
  src/main/java/com/kuit/findyou/domain/report/model/InterestProtectingReport.java
  src/main/java/com/kuit/findyou/domain/report/model/InterestReport.java
  src/main/java/com/kuit/findyou/domain/report/model/Neutering.java
  src/main/java/com/kuit/findyou/domain/report/model/ProtectingReport.java
  src/main/java/com/kuit/findyou/domain/report/model/Report.java
  src/main/java/com/kuit/findyou/domain/report/model/ReportAnimal.java
  src/main/java/com/kuit/findyou/domain/report/model/ReportedAnimalFeature.java
  src/main/java/com/kuit/findyou/domain/report/model/Sex.java
  src/main/java/com/kuit/findyou/domain/report/model/ViewedProtectingReport.java
  src/main/java/com/kuit/findyou/domain/report/model/ViewedReport.java
  src/main/java/com/kuit/findyou/domain/report/repository/AnimalFeatureRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/BreedRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/InterestProtectingReportRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/InterestReportRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/ProtectingReportRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/ReportAnimalRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/ReportRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/ReportedAnimalFeatureRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/ViewedProtectingReportRepository.java
  src/main/java/com/kuit/findyou/domain/report/repository/ViewedReportRepository.java
  src/main/java/com/kuit/findyou/domain/report/service/ProtectingAnimalInfoService.java
  src/main/java/com/kuit/findyou/domain/report/service/ReportAnimalInfoService.java
  src/main/java/com/kuit/findyou/global/common/model/BaseEntity.java
  src/main/java/com/kuit/findyou/global/common/model/BaseStatus.java
  src/test/java/com/kuit/findyou/domain/auth/repository/UserRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/AnimalFeatureRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/BreedRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/InterestProtectingReportTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/InterestReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ProtectingReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ReportAnimalRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ReportedAnimalFeatureRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ViewedProtectingReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ViewedReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/service/ProtectingAnimalInfoServiceTest.java
  src/test/java/com/kuit/findyou/domain/report/service/ReportAnimalInfoServiceTest.java
  src/test/resources/application.yml
Labels: 상균

#21 [Feat] #15: 이미지 업로드 관련 클래스 구현
  build.gradle
  src/main/java/com/kuit/findyou/domain/report/controller/ImageController.java
  src/main/java/com/kuit/findyou/domain/report/controller/ReportController.java
  src/main/java/com/kuit/findyou/domain/report/dto/ImageUploadDTO.java
  src/main/java/com/kuit/findyou/domain/report/exception/FileStorageException.java
  src/main/java/com/kuit/findyou/domain/report/exception_handler/ControllerAdvice.java
  src/main/java/com/kuit/findyou/domain/report/model/Image.java
  src/main/java/com/kuit/findyou/domain/report/model/Report.java
  src/main/java/com/kuit/findyou/domain/report/repository/ImageRepository.java
  src/main/java/com/kuit/findyou/domain/report/service/ImageService.java
  src/main/java/com/kuit/findyou/global/common/exception_handler/GlobalControllerAdvice.java
  src/test/java/com/kuit/findyou/domain/report/repository/InterestReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/repository/ViewedReportRepositoryTest.java
  src/test/java/com/kuit/findyou/domain/report/service/AnimalRetrieveServiceTest.java
  src/test/java/com/kuit/findyou/domain/report/service/ImageServiceTest.java
  src/test/java/com/kuit/findyou/domain/report/service/ReportAnimalInfoServiceTest.java
  src/test/java/com/kuit/findyou/domain/report/service/ReportAnimalRetrieveServiceTest.java
  uploads12381e42-1364-460c-a702-6a07db6d5842.jpg
  uploads3027d8ac-0747-415f-855d-be582c41420b.jpg
  uploads3de41cac-9ae5-4d9a-a6e5-ea4068b5a9a0.jpg
  uploads416d8105-aaee-4fbb-9ed3-df321209bad5.jpg
  uploads464790d5-dd33-4b1d-94e1-ae569b6ac815.jpg
  uploads6d678d4f-c811-4347-9394-ab4a7599220d.jpg
  uploads77ecd1c4-ead5-442c-8807-dcc9e75d9d0e.jpg
  uploads852c794a-dcca-426f-80f4-ead5226b8057.jpg
  uploads914eba80-8adf-4e5b-a328-9a8ca580e18d.jpg
  uploads930c6ffa-89e4-4694-8eff-96b459990fcc.jpg
  uploadsa315f105-ff15-4602-8a78-f18bc6e04215.jpg
  uploadsb0eb582c-9f28-4a13-b09a-035538fd7b5c.jpg
  uploadsb80d2ebf-55f5-42fc-9d83-868847a88b5c.jpg
  uploadsd866e45f-2108-4600-af50-244335b8f90c.jpg
  uploadsefdac565-56f0-4c6e-a3fc-c1cc0d372417.jpg
Labels: enhancement, 주연

#37 [Feat] 마이 페이지 - 닉네임 수정
  src/main/java/com/kuit/findyou/domain/auth/model/User.java
  src/main/java/com/kuit/findyou/domain/report/dto/Card.java
  src/main/java/com/kuit/findyou/domain/report/dto/ProtectingReportInfoDTO.java
  src/main/java/com/kuit/findyou/domain/report/dto/ReportInfoDTO.java
  src/main/java/com/kuit/findyou/domain/report/model/Breed.java
  src/main/java/com/kuit/findyou/domain/report/model/Report.java
  src/main/java/com/kuit/findyou/domain/report/service/AnimalRetrieveService.java
  src/main/java/com/kuit/findyou/domain/report/service/ProtectingAnimalInfoService.java
  src/main/java/com/kuit/findyou/domain/report/service/ProtectingAnimalRetrieveService.java
  src/main/java/com/kuit/findyou/domain/report/service/ReportAnimalInfoService.java
  src/main/java/com/kuit/findyou/domain/report/service/ReportAnimalRetrieveService.java
  src/main/java/com/kuit/findyou/domain/user/controller/UserController.java
  src/main/java/com/kuit/findyou/domain/user/dto/NewNicknameRequest.java
  src/main/java/com/kuit/findyou/domain/user/service/UserService.java
  src/test/java/com/kuit/findyou/domain/report/service/ProtectingAnimalInfoServiceTest.java
  src/test/java/com/kuit/findyou/domain/report/service/ReportAnimalInfoServiceTest.java
  src/test/java/com/kuit/findyou/user/UserServiceTest.java
Labels: 상균
